import { EB_Garamond, STIX_Two_Text } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import ScrollIndicator from "./components/ScrollIndicator/ScrollIndicator";

const EBGaramond = EB_Garamond({
   variable:"--font-eb-garamond",
   subsets: ["latin"],
});

const STIXTwoText = STIX_Two_Text({
  variable:"--font-stix-two-text",
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${EBGaramond.variable} ${STIXTwoText.variable}`}>
        <header style={{position: "fixed", top: 0, width: "100%"}}>
          <div >
            <h1>Linear Equations</h1>
            <Image
              src="/menu.svg"
              alt="menu"
              width={180}
              height={38}
              priority
            />
          </div>
          <ScrollIndicator isSticky={true}/>
        </header>
        {children}
      </body>
    </html>
  );
}
